name: Jest

on:
  push:
    branches: [ master ]

jobs:

  test:
    name: Test All
    runs-on: ubuntu-latest
    steps:

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
      id: nodejs

    - name: Check Out Source Code
      uses: actions/checkout@v3

    - name: Yarn Install
      run: yarn

    - name: Do Test
      run: yarn test

    - name: Move Coverage Report
      run: mv ./coverage/lcov-report ./public

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        user_name: Lewin Lan
        user_email: lewin.lan.cn@gmail.com
